default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: postgres
  password:

development:
  <<: *default
  database: takemeaway_development

test:
  <<: *default
  database: takemeaway_test

production:
  <<: *default
  database: takemeaway_production
  username: takemeaway
  password: <%= ENV['TAKEMEAWAY_DATABASE_PASSWORD'] %>
